Add circlci pre-commit

diff --git a/git/templates/hooks/pre-commit b/git/templates/hooks/pre-commit
--- a/git/templates/hooks/pre-commit
+++ b/git/templates/hooks/pre-commit
@@ -14,3 +14,15 @@ else
   # user.email is not empty
   exit 0
 fi
+
+# A git hook to make sure .circleci/config.yml is formatted correctly
+
+# The following line is needed by the CircleCI Local Build Tool (due to Docker interactivity)
+exec < /dev/tty
+
+# If validation fails, tell Git to stop and provide error message. Otherwise, continue.
+if ! eMSG=$(circleci config validate -c .circleci/config.yml); then
+  echo "CircleCI Configuration Failed Validation."
+  echo "$eMSG"
+  exit 1
+fi
